include: package:very_good_analysis/analysis_options.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
analyzer:
  language:
    strict-casts: true
    strict-raw-types: false

linter:
  rules:
    prefer_function_declarations_over_variables: false
    avoid_positional_boolean_parameters: false
    avoid_bool_literals_in_conditional_expressions: false
    avoid_redundant_argument_values: false
    avoid_dynamic_calls: false
    comment_references: false
    flutter_style_todos: true
    leading_newlines_in_multiline_strings: false
    lines_longer_than_80_chars: false
    no_default_cases: false
    prefer_asserts_with_message: false
    prefer_single_quotes: false
    public_member_api_docs: false
    omit_local_variable_types: false
    unnecessary_await_in_return: false
    unnecessary_lambdas: false
    