name: transora
description: "transforms audio recordings into interactive transcripts"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cupertino_icons: ^1.0.8
  file_picker: 10.1.9
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  go_router: ^15.1.2
  path_provider: 2.1.5
  sqflite_sqlcipher: ^3.1.0+1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
