name: Flutter CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

#      - name: Install jq (needed for flutter-action)
#        run: |
#          apt-get update
#          apt-get install -y jq curl unzip

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.27.1

#      - run: flutter pub get
      - run: flutter --version
#      - run: flutter build apk